"""Add accountability fields to members

Revision ID: 37e22dfaff85
Revises: 
Create Date: 2025-10-21 16:25:01.222111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e22dfaff85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('members', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('members', sa.Column('suspended_by', sa.UUID(), nullable=True))
    op.add_column('members', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('members', sa.Column('suspension_reason', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'members', 'users', ['suspended_by'], ['id'])
    op.create_foreign_key(None, 'members', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_column('members', 'suspension_reason')
    op.drop_column('members', 'suspended_at')
    op.drop_column('members', 'suspended_by')
    op.drop_column('members', 'approved_at')
    op.drop_column('members', 'approved_by')
    # ### end Alembic commands ###
