"""Add receipt fields to contributions

Revision ID: 52b7eddab128
Revises: 37e22dfaff85
Create Date: 2025-10-21 16:25:50.973002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b7eddab128'
down_revision = '37e22dfaff85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('receipt_s3_key', sa.String(length=500), nullable=True))
    op.add_column('contributions', sa.Column('receipt_s3_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'receipt_s3_url')
    op.drop_column('contributions', 'receipt_s3_key')
    # ### end Alembic commands ###
