"""PIVOT v2.0: Add profile tracking and probation system

Revision ID: 8a317fca7c64
Revises: 52b7eddab128
Create Date: 2025-10-23 22:28:41.533601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a317fca7c64'
down_revision = '52b7eddab128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probations_case_id'), 'probations', ['case_id'], unique=False)
    op.create_index(op.f('ix_probations_member_id'), 'probations', ['member_id'], unique=False)
    op.add_column('cases', sa.Column('case_number', sa.Integer(), nullable=False))
    op.add_column('cases', sa.Column('deceased_name', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('relationship', sa.Enum('MOTHER', 'FATHER', 'SPOUSE', 'SON', 'DAUGHTER', name='relationshiptype'), nullable=True))
    op.add_column('cases', sa.Column('date_of_death', sa.Date(), nullable=True))
    op.add_column('cases', sa.Column('verification_notes', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('total_amount_required', sa.Float(), nullable=True))
    op.add_column('cases', sa.Column('total_amount_collected', sa.Float(), nullable=False))
    op.add_column('cases', sa.Column('disbursement_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cases', sa.Column('confirmed_receipt', sa.Boolean(), nullable=False))
    op.alter_column('cases', 'affected_member_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('cases', 'relationship_to_reporter',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=True)
    op.add_column('contributions', sa.Column('case_id', sa.UUID(), nullable=False))
    op.add_column('contributions', sa.Column('contribution_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contributions', sa.Column('deadline', sa.DateTime(timezone=True), nullable=False))
    op.add_column('contributions', sa.Column('payment_reference', sa.String(length=255), nullable=True))
    op.alter_column('contributions', 'member_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('contributions', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_index('ix_contributions_payment_date', table_name='contributions')
    op.create_index(op.f('ix_contributions_case_id'), 'contributions', ['case_id'], unique=False)
    op.drop_constraint('contributions_member_id_fkey', 'contributions', type_='foreignkey')
    op.drop_constraint('contributions_verified_by_user_id_fkey', 'contributions', type_='foreignkey')
    op.create_foreign_key(None, 'contributions', 'cases', ['case_id'], ['id'])
    op.create_foreign_key(None, 'contributions', 'members', ['member_id'], ['id'])
    op.drop_column('contributions', 'receipt_s3_url')
    op.drop_column('contributions', 'payment_method')
    op.drop_column('contributions', 'verified_date')
    op.drop_column('contributions', 'notes')
    op.drop_column('contributions', 'payment_date')
    op.drop_column('contributions', 'receipt_s3_key')
    op.drop_column('contributions', 'transaction_reference')
    op.drop_column('contributions', 'verified_by_user_id')
    op.add_column('members', sa.Column('profile_completed', sa.Boolean(), nullable=False))
    op.add_column('members', sa.Column('profile_data', sa.JSON(), nullable=True))
    op.add_column('members', sa.Column('on_probation', sa.Boolean(), nullable=False))
    op.add_column('members', sa.Column('is_first_login', sa.Boolean(), nullable=False))
    op.drop_constraint('members_approved_by_fkey', 'members', type_='foreignkey')
    op.drop_constraint('members_suspended_by_fkey', 'members', type_='foreignkey')
    op.drop_column('members', 'suspended_by')
    op.drop_column('members', 'suspension_reason')
    op.drop_column('members', 'suspended_at')
    op.drop_column('members', 'approved_by')
    op.drop_column('members', 'approved_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('suspended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('suspension_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('members', sa.Column('suspended_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('members_suspended_by_fkey', 'members', 'users', ['suspended_by'], ['id'])
    op.create_foreign_key('members_approved_by_fkey', 'members', 'users', ['approved_by'], ['id'])
    op.drop_column('members', 'is_first_login')
    op.drop_column('members', 'on_probation')
    op.drop_column('members', 'profile_data')
    op.drop_column('members', 'profile_completed')
    op.add_column('contributions', sa.Column('verified_by_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('contributions', sa.Column('transaction_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('contributions', sa.Column('receipt_s3_key', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('contributions', sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('contributions', sa.Column('notes', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('contributions', sa.Column('verified_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('contributions', sa.Column('payment_method', postgresql.ENUM('MPESA', 'BANK_TRANSFER', 'CASH', 'CHEQUE', 'OTHER', name='paymentmethod'), autoincrement=False, nullable=False))
    op.add_column('contributions', sa.Column('receipt_s3_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.drop_constraint(None, 'contributions', type_='foreignkey')
    op.create_foreign_key('contributions_verified_by_user_id_fkey', 'contributions', 'users', ['verified_by_user_id'], ['id'])
    op.create_foreign_key('contributions_member_id_fkey', 'contributions', 'members', ['member_id'], ['member_id'])
    op.drop_index(op.f('ix_contributions_case_id'), table_name='contributions')
    op.create_index('ix_contributions_payment_date', 'contributions', ['payment_date'], unique=False)
    op.alter_column('contributions', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('contributions', 'member_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('contributions', 'payment_reference')
    op.drop_column('contributions', 'deadline')
    op.drop_column('contributions', 'contribution_date')
    op.drop_column('contributions', 'case_id')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.alter_column('cases', 'relationship_to_reporter',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cases', 'affected_member_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('cases', 'confirmed_receipt')
    op.drop_column('cases', 'disbursement_date')
    op.drop_column('cases', 'total_amount_collected')
    op.drop_column('cases', 'total_amount_required')
    op.drop_column('cases', 'verification_notes')
    op.drop_column('cases', 'date_of_death')
    op.drop_column('cases', 'relationship')
    op.drop_column('cases', 'deceased_name')
    op.drop_column('cases', 'case_number')
    op.drop_index(op.f('ix_probations_member_id'), table_name='probations')
    op.drop_index(op.f('ix_probations_case_id'), table_name='probations')
    op.drop_table('probations')
    # ### end Alembic commands ###
